name: Dispatch Notifications (Daily)

on:
  schedule:
    - cron: "0 3 * * *" # UTC 03:00 = KST 12:00
  workflow_dispatch: {}

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call dispatch-notifications (tax+station+manual)
        shell: bash
        run: |
          set -euo pipefail
          URL="https://tms-final.vercel.app/api/dispatch-notifications"
          if [ -n "${CRON_SECRET:=${{ secrets.CRON_SECRET }}}" ]; then
            curl -fsSL -X GET "$URL" \
              -H "x-cron-key: $CRON_SECRET" \
              -H "Accept: application/json" \
              -o response.json
          else
            curl -fsSL -X GET "$URL" -H "Accept: application/json" -o response.json
          fi
          echo "Response:" && cat response.json

