name: Dispatch Notifications (Daily)

on:
  schedule:
    - cron: "0 3 * * *" # UTC 03:00 = KST 12:00
  workflow_dispatch: {}

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call dispatch-notifications (tax+station+manual)
        run: |
          curl -sS -X GET "https://tms-final.vercel.app/api/dispatch-notifications" \
            -H "x-cron-key: ${{ secrets.CRON_SECRET }}" \
            -H "Accept: application/json" | tee response.json
          echo "Response:" && cat response.json
name: Dispatch Notifications (Daily)

on:
  schedule:
    # Run at 01:00 UTC every day (KST 10:00)
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      type:
        description: 'Notification type (optional: tax | station_schedule)'
        required: false
        default: tax

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Call dispatch-notifications
        shell: bash
        run: |
          set -euo pipefail
          URL="https://tms.watercharging.com/api/dispatch-notifications"
          if [ -n "${{ github.event.inputs.type || '' }}" ]; then
            URL="$URL?type=${{ github.event.inputs.type }}"
          fi
          if [ -n "${{ secrets.CRON_SECRET || '' }}" ]; then
            curl -sS -X POST -H "x-cron-key: ${{ secrets.CRON_SECRET }}" "$URL" | jq -r '.' || exit 1
          else
            curl -sS -X POST "$URL" | jq -r '.' || exit 1
          fi

